### ISSUE TITLE
Can input numbers in name field.

### ISSUE THREAD

**Issue by sophielevens** [fac-12/What-the-FAC-is-for-dinner#14]
😻 **LOVE THE LOOK OF THE SITE!** and it's super helpful and a great idea - hopefully we can use it to solve our dinner issues! 

Just a heads up that numbers can be put into the input boxes, [maybe this could be worth looking into?](https://stackoverflow.com/questions/19849189/js-function-to-allow-enter-only-letters-and-white-spaces) for next week regarding server side validation. 

<img width="1062" alt="screen shot 2017-12-01 at 10 10 47" src="https://user-images.githubusercontent.com/25961258/33478158-420b47a8-d680-11e7-9a99-ed5158238c6f.png">

**Comment by rb50** [comment]
Thanks for the feedback! We've now resolved this so it's not possible to put numbers in the name box 😸
