### ISSUE TITLE
Script injections

### ISSUE THREAD

**Issue by njseeto** [fac-12/What-the-FAC-is-for-dinner#18]
I don't know if you guys are using prepared statements in your queries, but the below may help:

```
 databaseConnection.query(
    'INSERT INTO users (name, location) VALUES ($1, $2)',
    [name, location],
    (err, res) => {
      if (err) {
        return cb(err);
      } else {
        cb(null, res);
      }
    }
  );
};
```
Also a [link to the script injection research](https://hackmd.io/IYBgHApgbCCMBmBaA7AJgCZICwCMDMqiAnHsITtCFlkRMvKqkA==)

I say this but our project is probably being hacked as we speak 💁

**Comment by morkeltry** [comment]
@njseeto that's the right way to paramaterise SQL queries. In `pg-pool`, as we use, the parameters need to be in that array *after* the query, not inside the query using template literals, which looks similar.

**Comment by rb50** [comment]
We've now changed the code to use prepared statements, thanks for your feedback!
